# Default config

spring.profiles: default

server:
  contextPath: /
  port: 8080
  address: localhost
  publicAddress: http://localhost:4200

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      max-swallow-size: -1
  data:
    mongodb:
      host: localhost
      port: 27017
      database: convrt_db

#cache
  cache:
    type: caffeine
    cache-names: query, video. autocomplete
    caffeine:
        spec: maximumSize=500, expireAfterAccess=1h

#jackson config
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

# Dev config
#spring.profiles: dev, local

logging.level.org.springframework.web: INFO

# Prod config
# spring.profiles: prod

