# Default config

spring.profiles: default

server:
  contextPath: /
  port: 8080
  address: localhost
  publicAddress: http://jeff-staging.mynetgear.com:4200

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      max-swallow-size: -1
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/convrt_me_dev
    username: root
    password: 1234
#    username: tripactions
#    password: prodActive00
    username: root
    password: root
#    username: tripactions
#    password: prodActive00
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: convrt_db
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.url=jdbc:mysql://localhost:3306/db_example
#spring.datasource.username=springuser
#spring.datasource.password=ThePassword

#cache
  cache:
    type: caffeine
    cache-names: search, video. autocomplete, recommended
    caffeine: 
        spec: maximumSize=500, expireAfterAccess=1h

#jackson config
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

# Dev config
#spring.profiles: dev, local

logging.level.org.springframework.web: INFO

# Prod config
# spring.profiles: prod

