# On command line: "java -Dspring.profiles.active=aws -jar <jar file name>"

server:
  contextPath: /
  port: 8083
  address: 172.31.10.241
  publicAddress: http://moup.io

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://convrt-me-aws.csx1pzmrhuek.us-west-1.rds.amazonaws.com:3306/convrt_me_aws
    username: admin
    password: aipas169+

  cache:
    type: caffeine
    cache-names: search, video, autocomplete, recommended
    caffeine:
        spec: maximumSize=500, expireAfterAccess=1m

logging:
  level:
    org:
      springframework:
        web: INFO
  file: spring-api.log

# WHEN CREATING A NEW DATABASE set the collation to: "utf8mb4 - default collation"
