# On command line: "java -Dspring.profiles.active=aws -jar <jar file name>"
# RUN THIS: nohup java -jar -Dspring.profiles.active=aws -server moup-api-1.0-SNAPSHOT.jar

server:
  contextPath: /
  port: 8083
  address: 172.31.80.247
  publicAddress: http://moup.io


subscriptionCallbackUrl: http://api.moup.io:8083

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://moup.cpfuzfu2kz7d.us-east-1.rds.amazonaws.com:3306/moup
    username: admin
    password: admin1234

  cache:
    type: caffeine
    cache-names: video, autocomplete
    caffeine:
        spec: maximumSize=500, expireAfterAccess=15m

logging:
  level:
    org:
      springframework:
        web: INFO
  file: spring-api.log

# WHEN CREATING A NEW DATABASE set the collation to: "utf8mb4 - default collation"
