# Default config

spring.profiles: default

server:
  contextPath: /
  port: 8083
  address: localhost
  publicAddress: http://localhost:4200

subscriptionCallbackUrl: http://21ab5097.ngrok.io

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/moup_dev
    username: root
    password: root

  cache:
    type: caffeine
    cache-names: video, autocomplete
    caffeine:
        spec: maximumSize=500, expireAfterAccess=15m

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

logging:
  level:
    org:
      springframework:
        web: INFO
  file: spring-api.log

# WHEN CREATING A NEW DATABASE set the collation to: "utf8mb4 - default collation"
